### ISSUE TITLE
Couldn't reproduce

### ISSUE THREAD

**Issue by blaines** [hashicorp/c1m#4]
Was trying to reproduce the c1m but couldn't get beyond the packer step for AWS. Also I don't have an Atlas username and it's not clear where to get one.

```
✘  ...hashicorp/c1m/packer   master ✔ 
$ packer build aws_utility.json
amazon-ebs output will be in this color.

1 error(s) occurred:

* Bad source 'packer/scripts/.': stat packer/scripts/.: no such file or directory
```

**Comment by justincampbell** [comment]
@blaines Packer will join the script path to the current working directory. So if the command ran was `packer build aws_utility.json`, it was ran from the `packer/` directory, so it's looking for `packer/packer/scripts`. Running `packer build packer/aws_utility.json` should resolve that issue.

You can sign up for an Atlas trial at https://atlas.hashicorp.com/account/new

Hope this helps!

**Comment by justincampbell** [comment]
Packer in Atlas has been deprecated, but feel free to reopen if you'd like to discuss this more. Thanks!
